import { CountryCodes } from "../models/country";

export const COUNTRY_CODES: CountryCodes = [
    { Name: 'Afghanistan', Code: 'AF', DialCode: '+93' },
    { Name: 'Albania', Code: 'AL', DialCode: '+355' },
    { Name: 'Algeria', Code: 'DZ', DialCode: '+213' },
    { Name: 'American Samoa', Code: 'AS', DialCode: '+1' },
    { Name: 'Andorra', Code: 'AD', DialCode: '+376' },
    { Name: 'Angola', Code: 'AO', DialCode: '+244' },
    { Name: 'Anguilla', Code: 'AI', DialCode: '+1' },
    { Name: 'Antarctica', Code: 'AQ', DialCode: '+672' },
    { Name: 'Antigua and Barbuda', Code: 'AG', DialCode: '+1' },
    { Name: 'Argentina', Code: 'AR', DialCode: '+54' },
    { Name: 'Armenia', Code: 'AM', DialCode: '+374' },
    { Name: 'Aruba', Code: 'AW', DialCode: '+297' },
    { Name: 'Australia', Code: 'AU', DialCode: '+61' },
    { Name: 'Austria', Code: 'AT', DialCode: '+43' },
    { Name: 'Azerbaijan', Code: 'AZ', DialCode: '+994' },
    { Name: 'Bahamas', Code: 'BS', DialCode: '+1' },
    { Name: 'Bahrain', Code: 'BH', DialCode: '+973' },
    { Name: 'Bangladesh', Code: 'BD', DialCode: '+880' },
    { Name: 'Barbados', Code: 'BB', DialCode: '+1' },
    { Name: 'Belarus', Code: 'BY', DialCode: '+375' },
    { Name: 'Belgium', Code: 'BE', DialCode: '+32' },
    { Name: 'Belize', Code: 'BZ', DialCode: '+501' },
    { Name: 'Benin', Code: 'BJ', DialCode: '+229' },
    { Name: 'Bermuda', Code: 'BM', DialCode: '+1' },
    { Name: 'Bhutan', Code: 'BT', DialCode: '+975' },
    { Name: 'Bolivia', Code: 'BO', DialCode: '+591' },
    { Name: 'Bosnia and Herzegovina', Code: 'BA', DialCode: '+387' },
    { Name: 'Botswana', Code: 'BW', DialCode: '+267' },
    { Name: 'Brazil', Code: 'BR', DialCode: '+55' },
    { Name: 'Brunei', Code: 'BN', DialCode: '+673' },
    { Name: 'Bulgaria', Code: 'BG', DialCode: '+359' },
    { Name: 'Burkina Faso', Code: 'BF', DialCode: '+226' },
    { Name: 'Burundi', Code: 'BI', DialCode: '+257' },
    { Name: 'Cambodia', Code: 'KH', DialCode: '+855' },
    { Name: 'Cameroon', Code: 'CM', DialCode: '+237' },
    { Name: 'Canada', Code: 'CA', DialCode: '+1' },
    { Name: 'Cape Verde', Code: 'CV', DialCode: '+238' },
    { Name: 'Cayman Islands', Code: 'KY', DialCode: '+1' },
    { Name: 'Central African Republic', Code: 'CF', DialCode: '+236' },
    { Name: 'Chad', Code: 'TD', DialCode: '+235' },
    { Name: 'Chile', Code: 'CL', DialCode: '+56' },
    { Name: 'China', Code: 'CN', DialCode: '+86' },
    { Name: 'Christmas Island', Code: 'CX', DialCode: '+53' },
    { Name: 'Cocos Islands', Code: 'CC', DialCode: '+61' },
    { Name: 'Colombia', Code: 'CO', DialCode: '+57' },
    { Name: 'Cook Islands', Code: 'CK', DialCode: '+682' },
    { Name: 'Costa Rica', Code: 'CR', DialCode: '+506' },
    { Name: "Cote D'Ivoire", Code: 'CI', DialCode: '+225' },
    { Name: 'Croatia', Code: 'HR', DialCode: '+385' },
    { Name: 'Cuba', Code: 'CU', DialCode: '+53' },
    { Name: 'Cyprus', Code: 'CY', DialCode: '+357' },
    { Name: 'Czech Republic', Code: 'CZ', DialCode: '+420' },
    { Name: 'Democratic Republic of the Congo', Code: 'CD', DialCode: '+243' },
    { Name: 'Denmark', Code: 'DK', DialCode: '+45' },
    { Name: 'Djibouti', Code: 'DJ', DialCode: '+253' },
    { Name: 'Dominica', Code: 'DM', DialCode: '+1' },
    { Name: 'Dominican Republic', Code: 'DO', DialCode: '+1' },
    { Name: 'East Timor', Code: 'TP', DialCode: '+670' },
    { Name: 'Ecuador', Code: 'EC', DialCode: '+593' },
    { Name: 'Egypt', Code: 'EG', DialCode: '+20' },
    { Name: 'El Salvador', Code: 'SV', DialCode: '+503' },
    { Name: 'Equatorial Guinea', Code: 'GQ', DialCode: '+240' },
    { Name: 'Eritrea', Code: 'ER', DialCode: '+291' },
    { Name: 'Estonia', Code: 'EE', DialCode: '+372' },
    { Name: 'Ethiopia', Code: 'ET', DialCode: '+251' },
    { Name: 'Falkland Islands', Code: 'FK', DialCode: '+500' },
    { Name: 'Faroe Islands', Code: 'FO', DialCode: '+298' },
    { Name: 'Federated States of Micronesia', Code: 'FM', DialCode: '+691' },
    { Name: 'Fiji', Code: 'FJ', DialCode: '+679' },
    { Name: 'Finland', Code: 'FI', DialCode: '+358' },
    { Name: 'France', Code: 'FR', DialCode: '+33' },
    { Name: 'French Guyana', Code: 'GF', DialCode: '+594' },
    { Name: 'French Polynesia', Code: 'PF', DialCode: '+689' },
    { Name: 'Gabon', Code: 'GA', DialCode: '+241' },
    { Name: 'Gambia', Code: 'GM', DialCode: '+220' },
    { Name: 'Georgia', Code: 'GE', DialCode: '+995' },
    { Name: 'Germany', Code: 'DE', DialCode: '+49' },
    { Name: 'Ghana', Code: 'GH', DialCode: '+233' },
    { Name: 'Gibraltar', Code: 'GI', DialCode: '+350' },
    { Name: 'Greece', Code: 'GR', DialCode: '+30' },
    { Name: 'Greenland', Code: 'GL', DialCode: '+299' },
    { Name: 'Grenada', Code: 'GD', DialCode: '+1' },
    { Name: 'Guadeloupe', Code: 'GP', DialCode: '+590' },
    { Name: 'Guam', Code: 'GU', DialCode: '+1' },
    { Name: 'Guatemala', Code: 'GT', DialCode: '+502' },
    { Name: 'Guinea', Code: 'GN', DialCode: '+224' },
    { Name: 'Guinea-Bissau', Code: 'GW', DialCode: '+245' },
    { Name: 'Guyana', Code: 'GY', DialCode: '+592' },
    { Name: 'Haiti', Code: 'HT', DialCode: '+509' },
    { Name: 'Honduras', Code: 'HN', DialCode: '+504' },
    { Name: 'Hong Kong', Code: 'HK', DialCode: '+852' },
    { Name: 'Hungary', Code: 'HU', DialCode: '+36' },
    { Name: 'Iceland', Code: 'IS', DialCode: '+354' },
    { Name: 'India', Code: 'IN', DialCode: '+91' },
    { Name: 'Indonesia', Code: 'ID', DialCode: '+62' },
    { Name: 'Iran', Code: 'IR', DialCode: '+98' },
    { Name: 'Iraq', Code: 'IQ', DialCode: '+964' },
    { Name: 'Ireland', Code: 'IE', DialCode: '+353' },
    { Name: 'Israel', Code: 'IL', DialCode: '+972' },
    { Name: 'Italy', Code: 'IT', DialCode: '+39' },
    { Name: 'Jamaica', Code: 'JM', DialCode: '+1' },
    { Name: 'Japan', Code: 'JP', DialCode: '+81' },
    { Name: 'Jordan', Code: 'JO', DialCode: '+962' },
    { Name: 'Kazakstan', Code: 'KZ', DialCode: '+7' },
    { Name: 'Kenya', Code: 'KE', DialCode: '+254' },
    { Name: 'Kiribati', Code: 'KI', DialCode: '+686' },
    { Name: 'Kuwait', Code: 'KW', DialCode: '+965' },
    { Name: 'Kyrgyzstan', Code: 'KG', DialCode: '+996' },
    { Name: 'Laos', Code: 'LA', DialCode: '+856' },
    { Name: 'Latvia', Code: 'LV', DialCode: '+371' },
    { Name: 'Lebanon', Code: 'LB', DialCode: '+961' },
    { Name: 'Lesotho', Code: 'LS', DialCode: '+266' },
    { Name: 'Liberia', Code: 'LR', DialCode: '+231' },
    { Name: 'Libya', Code: 'LY', DialCode: '+218' },
    { Name: 'Liechtenstein', Code: 'LI', DialCode: '+423' },
    { Name: 'Lithuania', Code: 'LT', DialCode: '+370' },
    { Name: 'Luxembourg', Code: 'LU', DialCode: '+352' },
    { Name: 'Macau', Code: 'MO', DialCode: '+853' },
    { Name: 'Macedonia', Code: 'MK', DialCode: '+389' },
    { Name: 'Madagascar', Code: 'MG', DialCode: '+261' },
    { Name: 'Malawi', Code: 'MW', DialCode: '+265' },
    { Name: 'Malaysia', Code: 'MY', DialCode: '+60' },
    { Name: 'Maldives', Code: 'MV', DialCode: '+960' },
    { Name: 'Mali', Code: 'ML', DialCode: '+223' },
    { Name: 'Malta', Code: 'MT', DialCode: '+356' },
    { Name: 'Marshall Islands', Code: 'MH', DialCode: '+692' },
    { Name: 'Martinique', Code: 'MQ', DialCode: '+596' },
    { Name: 'Mauritania', Code: 'MR', DialCode: '+222' },
    { Name: 'Mauritius', Code: 'MU', DialCode: '+230' },
    { Name: 'Mayotte', Code: 'YT', DialCode: '+269' },
    { Name: 'Mexico', Code: 'MX', DialCode: '+52' },
    { Name: 'Moldova', Code: 'MD', DialCode: '+373' },
    { Name: 'Monaco', Code: 'MC', DialCode: '+377' },
    { Name: 'Mongolia', Code: 'MN', DialCode: '+976' },
    { Name: 'Montserrat', Code: 'MS', DialCode: '+1' },
    { Name: 'Morocco', Code: 'MA', DialCode: '+212' },
    { Name: 'Mozambique', Code: 'MZ', DialCode: '+258' },
    { Name: 'Myanmar', Code: 'MM', DialCode: '+95' },
    { Name: 'Namibia', Code: 'NA', DialCode: '+264' },
    { Name: 'Nauru', Code: 'NR', DialCode: '+674' },
    { Name: 'Nepal', Code: 'NP', DialCode: '+977' },
    { Name: 'Netherlands', Code: 'NL', DialCode: '+31' },
    { Name: 'Netherlands Antilles', Code: 'AN', DialCode: '+599' },
    { Name: 'New Caledonia', Code: 'NC', DialCode: '+687' },
    { Name: 'New Zealand', Code: 'NZ', DialCode: '+64' },
    { Name: 'Nicaragua', Code: 'NI', DialCode: '+505' },
    { Name: 'Niger', Code: 'NE', DialCode: '+227' },
    { Name: 'Nigeria', Code: 'NG', DialCode: '+234' },
    { Name: 'Niue', Code: 'NU', DialCode: '+683' },
    { Name: 'Norfolk Island', Code: 'NF', DialCode: '+672' },
    { Name: 'North Korea', Code: 'KP', DialCode: '+850' },
    { Name: 'Northern Mariana Islands', Code: 'MP', DialCode: '+1' },
    { Name: 'Norway', Code: 'NO', DialCode: '+47' },
    { Name: 'Oman', Code: 'OM', DialCode: '+968' },
    { Name: 'Pakistan', Code: 'PK', DialCode: '+92' },
    { Name: 'Palau', Code: 'PW', DialCode: '+680' },
    { Name: 'Palestinian State', Code: 'PS', DialCode: '+970' },
    { Name: 'Panama', Code: 'PA', DialCode: '+507' },
    { Name: 'Papua New Guinea', Code: 'PG', DialCode: '+675' },
    { Name: 'Paraguay', Code: 'PY', DialCode: '+595' },
    { Name: 'Peru', Code: 'PE', DialCode: '+51' },
    { Name: 'Philippines', Code: 'PH', DialCode: '+63' },
    { Name: 'Poland', Code: 'PL', DialCode: '+48' },
    { Name: 'Portugal', Code: 'PT', DialCode: '+351' },
    { Name: 'Puerto Rico', Code: 'PR', DialCode: '+1' },
    { Name: 'Qatar', Code: 'QA', DialCode: '+974' },
    { Name: 'Republic of the Congo', Code: 'CG', DialCode: '+242' },
    { Name: 'Reunion', Code: 'RE', DialCode: '+262' },
    { Name: 'Romania', Code: 'RO', DialCode: '+40' },
    { Name: 'Russian Federation', Code: 'RU', DialCode: '+7' },
    { Name: 'Rwanda', Code: 'RW', DialCode: '+250' },
    { Name: 'Saint Helena', Code: 'SH', DialCode: '+290' },
    { Name: 'Saint Kitts and Nevis', Code: 'KN', DialCode: '+1' },
    { Name: 'Saint Lucia', Code: 'LC', DialCode: '+1' },
    { Name: 'Saint Pierre and Miquelon', Code: 'PM', DialCode: '+508' },
    { Name: 'Saint Vincent and the Grenadines', Code: 'VC', DialCode: '+1' },
    { Name: 'Samoa', Code: 'WS', DialCode: '+685' },
    { Name: 'San Marino', Code: 'SM', DialCode: '+378' },
    { Name: 'Sao Tome and Principe', Code: 'ST', DialCode: '+239' },
    { Name: 'Saudi Arabia', Code: 'SA', DialCode: '+966' },
    { Name: 'Senegal', Code: 'SN', DialCode: '+221' },
    { Name: 'Seychelles', Code: 'SC', DialCode: '+248' },
    { Name: 'Sierra Leone', Code: 'SL', DialCode: '+232' },
    { Name: 'Singapore', Code: 'SG', DialCode: '+65' },
    { Name: 'Slovakia', Code: 'SK', DialCode: '+421' },
    { Name: 'Slovenia', Code: 'SI', DialCode: '+386' },
    { Name: 'Solomon Islands', Code: 'SB', DialCode: '+677' },
    { Name: 'Somalia', Code: 'SO', DialCode: '+252' },
    { Name: 'South Africa', Code: 'ZA', DialCode: '+27' },
    { Name: 'South Korea', Code: 'KR', DialCode: '+82' },
    { Name: 'Spain', Code: 'ES', DialCode: '+34' },
    { Name: 'Sri Lanka', Code: 'LK', DialCode: '+94' },
    { Name: 'Sudan', Code: 'SD', DialCode: '+249' },
    { Name: 'Suriname', Code: 'SR', DialCode: '+597' },
    { Name: 'Swaziland', Code: 'SZ', DialCode: '+268' },
    { Name: 'Sweden', Code: 'SE', DialCode: '+46' },
    { Name: 'Switzerland', Code: 'CH', DialCode: '+41' },
    { Name: 'Syria', Code: 'SY', DialCode: '+963' },
    { Name: 'Taiwan', Code: 'TW', DialCode: '+886' },
    { Name: 'Tajikistan', Code: 'TJ', DialCode: '+992' },
    { Name: 'Tanzania', Code: 'TZ', DialCode: '+255' },
    { Name: 'Thailand', Code: 'TH', DialCode: '+66' },
    { Name: 'Tokelau', Code: 'TK', DialCode: '+690' },
    { Name: 'Tonga', Code: 'TO', DialCode: '+676' },
    { Name: 'Trinidad and Tobago', Code: 'TT', DialCode: '+1' },
    { Name: 'Tunisia', Code: 'TN', DialCode: '+216' },
    { Name: 'Turkey', Code: 'TR', DialCode: '+90' },
    { Name: 'Turkmenistan', Code: 'TM', DialCode: '+993' },
    { Name: 'Turks and Caicos Islands', Code: 'TC', DialCode: '+1' },
    { Name: 'Tuvalu', Code: 'TV', DialCode: '+688' },
    { Name: 'Uganda', Code: 'UG', DialCode: '+256' },
    { Name: 'Ukraine', Code: 'UA', DialCode: '+380' },
    { Name: 'Union of the Comoros', Code: 'KM', DialCode: '+269' },
    { Name: 'United Arab Emirates', Code: 'AE', DialCode: '+971' },
    { Name: 'United Kingdom', Code: 'GB', DialCode: '+44' },
    { Name: 'United States', Code: 'US', DialCode: '+1' },
    { Name: 'Uruguay', Code: 'UY', DialCode: '+598' },
    { Name: 'Uzbekistan', Code: 'UZ', DialCode: '+998' },
    { Name: 'Vanuatu', Code: 'VU', DialCode: '+678' },
    { Name: 'Vatican City State', Code: 'VA', DialCode: '+418' },
    { Name: 'Venezuela', Code: 'VE', DialCode: '+58' },
    { Name: 'Vietnam', Code: 'VN', DialCode: '+84' },
    { Name: 'US Virgin Islands', Code: 'VQ', DialCode: '+1' },
    { Name: 'British Virgin Islands', Code: 'VI', DialCode: '+1' },
    { Name: 'Wallis and Futuna Islands', Code: 'WF', DialCode: '+681' },
    { Name: 'Yemen', Code: 'YE', DialCode: '+967' },
    { Name: 'Zambia', Code: 'ZM', DialCode: '+260' },
    { Name: 'Zimbabwe', Code: 'ZW', DialCode: '+263' },
  ];
  